# Generated by Django 5.0.1 on 2024-01-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='illustration',
            field=models.ImageField(null=True, upload_to='illustration/'),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
