# Generated by Django 5.0.1 on 2024-01-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_admin', '0004_alter_article_graphics_and_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablegraphicpair',
            name='html_table',
            field=models.FileField(blank=True, null=True, upload_to='html_tables/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
